name: .NET Core CI

on:
  push:
    branches:
      - master
      - Dev
  pull_request:
    branches:
      - master
      - Dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: Install dependencies
      run: dotnet restore

    - name: Build the project
      run: dotnet build --configuration Release

    - name: Run tests
      run: dotnet test ./Depovs-Integracion-Continua.sln --verbosity normal